In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

import pandas as pd
from sklearn import preprocessing
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import joblib
# import numpy as np

In [2]:
df=pd.read_csv("data/data500.csv")
df.head(30)

ARSHIYA  F  32   sc  45  0  5  45.1  54  56  45.2  1
0         CHARVI CHHABRA  F  60  gen  76  0  4    70  78  65    74  0
1         CHELSI CHAUHAN  F  34  gen  87  0  7    45  65  45    56  0
2           DEEPTI VERMA  F  45   st  65  0  5    33  34  67    78  1
3         GAURANGI JHALA  F  45  obc  75  0  5    78  56  78    90  0
4          GORISHA ARORA  F  23   sc  89  0  5     6  10   5     3  0
5         HALEEMA SHAMSI  F  67   st  76  0  4    66  67  87    67  0
6         HARSHITA SINGH  F  23  gen  56  0  4    67  56  78    76  0
7       HEPHZIBAH WALTER  F  56  gen  45  1  7    34  34  67    23  1
8       ISHA RATAN JOSHI  F  78  gen  56  0  5    98  89  90    99  1
9   JENNIFER PETER DAVID  F  19  gen  76  0  6    76  78  98    78  0
10          JESSICA LALL  F  57   sc  65  0  6    54  45  67    89  0
11            JUHI BOHRA  F  89   st  45  0  6    67  45  87    66  0
12        KALPANA KUMARI  F  56  gen  65  0  5    45  45  67    34  0
13       KASHISH BADLANI  F  47  gen  87  0  7    34  34  56    65  1
14         KHUSHI MISHRA  F  87  obc  76  0  4    23  23  41    21  0
15          KOMAL PAREEK  F  23  obc  54  0  5    43  34  54    34  1
16             LUBNA ALI  F  67  gen  32  0  6     5  45  33    55  1
17        NIYATI KAUSHIK  F  45   sc  67  0  4    46  34  43    45  0
18         PALLAVI JOSHI  F  89   sc  87  0  5    87  89  78    60  0
19          PARUL SHARMA  F  54   st  85  0  6    45  65  44    34  0
20      PRIYANSHI SHARMA  F  67  gen  56  0  5    34  25  46    45  0
21        RIYA  A MATHEW  F  35   st  64  0  6    24  23  43    12  1
22            RIYA DUSAD  F  75  gen  76  0  5    43  44  34    23  0
23        RUCHIKA BAIRWA  F  43  gen  56  0  5    43  23  56    34  0
24       RUPAKSHI SHARMA  F  76  gen  43  0  5    23  23  34    21  1
25           SABRINA ALI  F  65  gen  70  0  5    23  21  23    32  0
26        SALONI VISHNOI  F  86  gen  45  0  5    54  54  65    43  1
27       SHIVANGI SHARMA  F  55  gen  76  1  5    65  65  67    87  0
28         SHIVI PRADHAN  F  45   sc  40  1  5    89  79  89    78  1
29           SIMRAN PURI  F  65   st  75  0  4    43  45  65    43  0

In [3]:
df.columns=["Name","gender","marks_1","caste","marks_2","Disabled","Attendance","marks_3","marks_4","marks_5","marks_6","Dropout"]

In [4]:
df

Name gender  marks_1 caste  marks_2  Disabled  \
0            CHARVI CHHABRA      F       60   gen       76         0   
1            CHELSI CHAUHAN      F       34   gen       87         0   
2              DEEPTI VERMA      F       45    st       65         0   
3            GAURANGI JHALA      F       45   obc       75         0   
4             GORISHA ARORA      F       23    sc       89         0   
..                      ...    ...      ...   ...      ...       ...   
444       TUSHAR KHANDELWAL      M       40    sc       31         0   
445            VARUN PAREEK      M       45   obc       56         0   
446            VISHAL RAWAT      M       50    sc       57         0   
447  YUVRAJ SINGH SHEKHAWAT      M       35    st       72         0   
448           AASTHA MISHRA      F       40    sc       16         0   

     Attendance  marks_3  marks_4  marks_5  marks_6  Dropout  
0             4       70       78       65       74        0  
1             7       45       65       45       56        0  
2             5       33       34       67       78        1  
3             5       78       56       78       90        0  
4             5        6       10        5        3        0  
..          ...      ...      ...      ...      ...      ...  
444           6       28       29       27       28        1  
445           5       23       20       26       28        1  
446           4       26       29       20       26        1  
447           4       24       20       26       25        1  
448           6       19       17       15       24        1  

[449 rows x 12 columns]

In [5]:
df_final=df[["Name","gender","caste","Disabled","Attendance","marks_1","marks_2","marks_3","marks_4","marks_5","marks_6","Dropout"]]

In [6]:
df_final

Name gender caste  Disabled  Attendance  marks_1  \
0            CHARVI CHHABRA      F   gen         0           4       60   
1            CHELSI CHAUHAN      F   gen         0           7       34   
2              DEEPTI VERMA      F    st         0           5       45   
3            GAURANGI JHALA      F   obc         0           5       45   
4             GORISHA ARORA      F    sc         0           5       23   
..                      ...    ...   ...       ...         ...      ...   
444       TUSHAR KHANDELWAL      M    sc         0           6       40   
445            VARUN PAREEK      M   obc         0           5       45   
446            VISHAL RAWAT      M    sc         0           4       50   
447  YUVRAJ SINGH SHEKHAWAT      M    st         0           4       35   
448           AASTHA MISHRA      F    sc         0           6       40   

     marks_2  marks_3  marks_4  marks_5  marks_6  Dropout  
0         76       70       78       65       74        0  
1         87       45       65       45       56        0  
2         65       33       34       67       78        1  
3         75       78       56       78       90        0  
4         89        6       10        5        3        0  
..       ...      ...      ...      ...      ...      ...  
444       31       28       29       27       28        1  
445       56       23       20       26       28        1  
446       57       26       29       20       26        1  
447       72       24       20       26       25        1  
448       16       19       17       15       24        1  

[449 rows x 12 columns]

In [7]:
class MultiColumnLabelEncoder:
    def __init__(self, columns=None):
        self.columns = columns  # array of column names to encode

    def fit(self, X, y=None):
        return self # not relevant here

    def transform(self, X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname, col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self, X, y=None):
        return self.fit(X, y).transform(X)


In [57]:
def generateModel(file, _id):

    dataset = MultiColumnLabelEncoder(columns=['gender', 'caste']).fit_transform(file)

    array = dataset.values
    X = array[:, 1:10]
    Y = array[:, 11]
    # print(Y)
    Y = Y.astype('int')

    model = DecisionTreeClassifier()
    model.fit(X, Y)
    filename = 'schoolModels/' + _id + '.pkl'
    joblib.dump(model, filename)

    return True

In [20]:
def get_prediction(data, _id):

    filename = 'schoolModels/' + _id + '.pkl'
    predict_from_joblib = joblib.load(filename)

    X_predict = {}
    for key, value in data.items():
        X_predict[key] = [value]

    X_predict = pd.DataFrame(data, index=[0])

    le = preprocessing.LabelEncoder()

    X_predict['gender'] = le.fit_transform(X_predict['gender'])
    X_predict['caste'] = le.fit_transform(X_predict['caste'])

    X_predict.to_numpy()
    prediction = predict_from_joblib.predict(X_predict)

    return prediction

In [58]:
df_final = MultiColumnLabelEncoder(columns=['gender', 'caste']).fit_transform(df_final)

array = df_final.values
X = array[:, 1:10]
Y = array[:, 11]
# print(Y)
Y = Y.astype('int')



In [59]:
X

array([[0, 0, 0, ..., 70, 78, 65],
       [0, 0, 0, ..., 45, 65, 45],
       [0, 4, 0, ..., 33, 34, 67],
       ...,
       [1, 3, 0, ..., 26, 29, 20],
       [1, 4, 0, ..., 24, 20, 26],
       [0, 3, 0, ..., 19, 17, 15]], dtype=object)

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [61]:
X_train

array([[1, 0, 0, ..., 35, 31, 32],
       [0, 4, 0, ..., 35, 45, 54],
       [1, 1, 0, ..., 72, 72, 72],
       ...,
       [1, 1, 0, ..., 64, 60, 65],
       [0, 1, 0, ..., 12, 13, 2],
       [0, 4, 0, ..., 69, 73, 63]], dtype=object)

In [62]:
y_test,len(y_test)

(array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 0]),
 135)

In [63]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [64]:
preds=model.predict(X_test)
preds

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0])

In [65]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0])

In [66]:
df_pred=pd.DataFrame({"original":y_test,"predictions":preds})
df_pred

original  predictions
0           0            0
1           1            0
2           1            0
3           0            0
4           0            0
..        ...          ...
130         0            0
131         0            0
132         0            0
133         1            1
134         0            0

[135 rows x 2 columns]

In [67]:
from sklearn.metrics import accuracy_score

In [68]:
print("Accuracy Score : ",round(accuracy_score(y_test,preds),2)*100)

Accuracy Score :  83.0


In [69]:
filename = 'schoolModels/' + 'try1.pkl'
joblib.dump(model, filename)

['schoolModels/try1.pkl']

In [70]:
X_train[0].shape


(9,)

In [72]:
X_train[0]

array([1, 0, 0, 5, 50, 11, 35, 31, 32], dtype=object)

## Custom Input :

In [71]:
filename = 'schoolModels/' + 'try1.pkl'
model=joblib.load(filename)

In [73]:
input_val=[1,1,0,3,20,20,10,20,10]


In [74]:
model.predict(np.array(input_val).reshape(1,-1))

array([1])